name: medisync_app
description: MediSync 360 - Centralized Healthcare Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

  # Networking
  http: ^1.2.1

  # Local storage
  shared_preferences: ^2.2.3

  # Push notifications
  firebase_core: ^3.3.0
  firebase_messaging: ^15.1.0
  flutter_inappwebview: ^6.1.5

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.3

flutter:
  uses-material-design: true